// <auto-generated />
namespace 縱火0709.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class create_user_account : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(create_user_account));
        
        string IMigrationMetadata.Id
        {
            get { return "202110060839413_create_user_account"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
