// <auto-generated />
namespace 縱火0709.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class user_delete_setUp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(user_delete_setUp));
        
        string IMigrationMetadata.Id
        {
            get { return "202110060732233_user_delete_setUp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
